name: CD

on:
  workflow_run:
    workflows: ['CI']
    types:
      - completed
    branches:
      - main

jobs:
  rust-pkg-cd:
    name: Rust package CD
    runs-on: ubuntu-latest
    steps:
      - uses: actalog/check-ci@main
      - uses: actions/checkout@v4
      - uses: actalog/rust-pkg-cd@v1
        with:
          cargo-registry-token: ${{ secrets.CARGO_REGISTRY_TOKEN }}
