name: CI

on:
  - pull_request
  - push
  - workflow_dispatch

jobs:
  rust-ci:
    name: Rust CI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actalog/rust-ci@v1
